# Generated by Django 5.0.6 on 2024-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MocieInfo',
            new_name='MovieInfo',
        ),
    ]
