# Generated by Django 5.0.6 on 2024-05-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieinfo_poster_alter_movieinfo_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
